spring:
  profiles:
    active: prod
    #active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.81.100:3306/light?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT
    username: root
    password: 123456

  jpa:
    hibernate:
    ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  show-sql: true

